### ISSUE TITLE
训练数据格式问题

### ISSUE THREAD

**Issue by zhangzhiyi0108** [Frozenmad/AMN_SRL#1]
请问训练，测试，验证需要什么样的数据形式

**Comment by zhangzhiyi0108** [comment]
您能提供一下预处理数据的代码吗

**Comment by zhangzhiyi0108** [comment]
就是如何得到train.txt dev.txt和test.txt文件的

**Comment by Frozenmad** [comment]
您好，应该是原始的conll09数据集格式经过重命名就可以直接用的。预处理的代码是preprocess.py，使用说明可以参考README

**Comment by zhangzhiyi0108** [comment]
抱歉，我实在找不到具体怎么用，你能提供一下数据吗？，如果数据不公开的话能方便提供一个数据的例子吗

**Comment by Frozenmad** [comment]
您好，您可以参考[conll 2009官方网站](https://ufal.mff.cuni.cz/conll2009-st/task-description.html)给出的conll09的英文数据集格式。

**Comment by zhangzhiyi0108** [comment]
太感谢你了，非常不幸运的是我下载到了train.txt，但是dev.txt和test.txt没下载到，因为提示说下载链接失效了

**Comment by zhangzhiyi0108** [comment]
如果想在window10 中运行get_dis.py文件，libtest = ctypes.cdll.LoadLibrary('./distance/xh_dis.so')这句应该怎么运用，运行时报这样的错误
Traceback (most recent call last):
  File "D:/Python/WorkSpace/AMN_SRL/distance/get_dis.py", line 2, in <module>
    libtest = ctypes.cdll.LoadLibrary('./distance/xh_dis.so')
  File "D:\Python\Anaconda3\envs\python35\lib\ctypes\__init__.py", line 429, in LoadLibrary
    return self._dlltype(name)
  File "D:\Python\Anaconda3\envs\python35\lib\ctypes\__init__.py", line 351, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: [WinError 126] 找不到指定的模块。

**Comment by Frozenmad** [comment]
这个应该是平台问题，请使用linux来调用相关模块。xh_dis.so这个文件目前是在linux下编译的链接库，暂不支持Windows，不好意思。

**Comment by zhangzhiyi0108** [comment]
好的，谢谢你
